import express from 'express';
import cors from 'cors';
import path from 'path';
const {exec} = require('child_process');

import {Request} from 'express';

const app = express();
const port = 3000;

//Declare __dirname so Typescript recognizes it
declare const __dirname: any;

// Set the view engine to EJS
app.set('view engine', 'ejs');

// Automatically get values from json responses
app.use(express.json());

// Set the views directory to look for EJS templates
// app.set('views', path.join(__dirname, 'views'));
app.use(express.static(path.join(__dirname, '../frontend/src/views')));

// Allows requests from the front end on a different port
app.use(cors({
    origin: 'http://localhost:5173',
    optionsSuccessStatus: 200 // Some legacy browsers choke on 204
}))

let currentProcess = null;

app.get('/test', (req, res) =>{
    const pythonPath = path.join(__dirname, "../../launch.py");

    if(currentProcess != null){
        currentProcess.kill();
        currentProcess = null;
    }

    currentProcess = exec(`python ${pythonPath} 0`, (error, stdout, stderr) => {
        if(error){
            console.error(error);
            return res.status(500).send(JSON.stringify({
                error:`Error executing python: ${error.message}`
            }))
        }

        if(stderr){
            console.error(`stderr: ${stderr}`)
            return res.status(500).send(JSON.stringify({
                error: `stderr: ${stderr}`
            }))
        }

        res.send(JSON.stringify({
            message: stdout
        }))
    })
})

app.get('/', (req, res) => {
    res.send('Hello World!');
})

app.get('/index', (req, res) => {
    res.sendFile(path.join(__dirname, '../src/views/index.html'));

    // Data that you want to pass to the EJS template
    // const data = {
    //     title: 'Dynamic Page',
    //     message: 'This is a dynamic message generated by Express and EJS!',
    // };

    // // Render the page with dynamic data
    // res.render('index', data);
})

app.get('/index.js', (req, res) => {
    console.log("serving index.js");
    res.set('Content-Type', 'application/javascript'); // Ensure the MIME type is correct
    res.sendFile(path.join(__dirname, '../src/index.js'));
});

app.listen(port, () => {
    console.log(`Server is running on http://localhost:${port}`);
})